/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vladek (https://sketchfab.com/vladek27)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-living-room-df179eebec234798aa7fbe6c7eaf492a
Title: Low poly living room
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame, useThree} from '@react-three/fiber'
import {a} from '@react-spring/three'

import roomScene from '../assets/3d/room.glb'

const Room = (props) => {
  const roomRef = useRef();
  const { nodes, materials } = useGLTF(roomScene)
  return (
    <a.group ref = {roomRef}{...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </a.group>
  )
}

export default Room;